version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data.db:/app/data.db
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    depends_on:
      - backend
    restart: unless-stopped